name: Botón de replit en README
on: [create]
jobs:
  actualizar_readme:
    name: Modificar el README
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v2.3.2

      - name: Modificar el archivo README.md
        run: |
          echo -e "[![Replit](https://docs.replit.com/images/repls/run-on-replit.svg)](https://replit.com/github/${GITHUB_REPOSITORY})\n$(cat README.md)" > README.md
          cat README.md

      - name: Commit y push de cambios
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

          git add -A
          git commit -m "chore(README): botón de replit"
          git push
